---
title: "04_graficos_extra"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(data.table)
library(ggplot2)
library(lubridate)
library(dplyr)
library(stringr)
library(metR)
library(patchwork)

map <- rnaturalearth::ne_states(country = c("argentina", "Brazil", "Chile", "Uruguay", "Paraguay", "Bolivia"), returnclass = "sf")
```


```{r}
files <- list.files("/home/paola.corrales/datosmunin/RRA_Fcst/estadisticos/", 
                    pattern = "espacial",
                    full.names = TRUE)


est_espacial <- lapply(files, function(f) {
  var <- str_extract(f, "\\d{5}")

  tmp <- fread(f) %>% 
    .[, var := var] %>%
    .[, fecha.ini := ymd_hms(fecha.ini)] %>%
    .[, hora.ini := hour(fecha.ini)] %>%
    .[]

  return(tmp)
} ) %>% 
  rbindlist() 

est_espacial[, var.type := case_when(var %in% c(2819, 82819) ~ "u",
                       var %in% c(2820, 82820) ~ "v",
                       var %in% c(3073, 83073) ~ "t",
                       var %in% c(3330, 83330) ~ "q",
                       var %in% c(3331, 83331) ~ "rh",
                       var %in% c(4001) ~ "dBz",
                       var %in% c(14593) ~ "p")]
```

```{r}
est_espacial[, .(rmse.mean = mean(rmse, na.rm = TRUE),
                 bias.mean = mean(bias, na.rm = TRUE)), 
             by = .(var.type, hora.ini, verif, lon, lat)] %>% 
  .[verif == 24 & hora.ini %in% c(0, 6, 12, 18) & !(var.type %in% c("rh", "p", "t")) & 
      rmse.mean < 7] %>% 
  na.omit() %>% 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_point(aes(color = rmse.mean)) +
  # scale_color_viridis_c() +
    scale_color_viridis_c(name = "RMSE", guide = guide_colorbar(nbin = 10, 
                                                            raster = FALSE,
                                                            barheight = 10, 
                                                            ticks = FALSE,
                                                            order = 1), 
                        breaks = seq(0, 5, 1), limits = c(NA, 5)) +
  # scale_size_area(max_size = 4, guide =  "none") +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA) +
  coord_sf(ylim = c(-38, -25), xlim = c(-67, -56)) +
  labs(x = "Longitude", y = "Latitude") +
  facet_grid(var.type ~ hora.ini) +
  theme_linedraw(base_size = 15) +
  theme(strip.background = element_blank(),
        strip.text = element_text(color = "black"),
        panel.grid = element_line(color = "grey80"))

ggsave("fig/rmse_espacial_uv.pdf", dpi = 300, width = 30, height = 20, units = "cm")
```


```{r}
est_espacial[, .(rmse.mean = mean(rmse, na.rm = TRUE),
                 bias.mean = mean(bias, na.rm = TRUE)), 
             by = .(var.type, hora.ini, verif, lon, lat)] %>% 
  .[verif == 24 & hora.ini %in% c(0, 6, 12, 18) & !(var.type %in% c("rh", "p", "t")) & 
      abs(bias.mean) <= 5] %>% 
  na.omit() %>% 
  ggplot(aes(ConvertLongitude(lon), lat)) +
  geom_point(aes(color = bias.mean)) +
  # scale_color_divergent() +
    scale_color_divergent(name = "BIAS", guide = guide_colorbar(nbin = 10,
                                                            raster = FALSE,
                                                            barheight = 10,
                                                            ticks = FALSE,
                                                            order = 1),
                        breaks = seq(-5, 5, 1), limits = c(-5, 5)) +
  # scale_size_area(max_size = 4, guide =  "none") +
  geom_sf(data = map, inherit.aes = FALSE, fill = NA) +
  coord_sf(ylim = c(-38, -25), xlim = c(-67, -56)) +
  labs(x = "Longitude", y = "Latitude") +
  facet_grid(var.type ~ hora.ini) +
  theme_linedraw(base_size = 15) +
  theme(strip.background = element_blank(),
        strip.text = element_text(color = "black"),
        panel.grid = element_line(color = "grey80"))

ggsave("fig/bias_espacial_uv.pdf", dpi = 300, width = 30, height = 20, units = "cm")
```
