---
title: "05_sondeos.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(metR)
library(lubridate)

rra_proj = "+proj=lcc +lat_1=-34.0 +lat_2=-34.0 +lat_0=-34.0 +lon_0=-60.0 +a=6370000 +b=6370000"

read_radiosonde_relampago <- function(file){
  # Leo línea por línea
  lines <- readLines(file)
  
  # Indices donde comienza cada sondeo
  idx <- which(grepl("Data Type:", lines))
  idx <- c(idx, length(lines)+1)
  soundings <- list()
  for (i in seq_len(length(idx)-1)) { 
    
    out <- read.table(text = lines[(idx[i] + 15):(idx[i + 1] - 1)]) %>% 
      as.data.table()
    
    names <- strsplit(lines[idx[i] + 12], " ")[[1]]
    names <- names[names != ""]
    colnames(out) <- names
    
    launch <- lubridate::ymd_hms(strsplit(lines[idx[i] + 4], "    ")[[1]][2])
    nominal_launch <- lubridate::ymd_hms(strsplit(lines[idx[i] + 11], "):")[[1]][2])
    site <- strsplit(lines[idx[i] + 2], "         ")[[1]][2]  
    
    out <- out[, ":="(Site = site,
                      Nominal_launch_time = nominal_launch,
                      Launch_time = launch)] %>% 
      .[, Time := seconds(Time) + Launch_time] %>% 
      .[, lapply(.SD, function(x) replace(x, as.character(x) %in% c("999", "9999", "999.0"), NA))] %>% 
      .[]
    if (length(colnames(out) == 24)) {
      colnames(out) <- c("time", "p", "t", "td", "rh", "u", "v", "spd", "dir", "w", "lon", "lat", "ele", 
                         "azi", "alt", "qp", "qt", "qrh", "qu", "qv", "qdZ", "site", "nominal_launch_time", 
                         "launch_time")
    } else {
      colnames(out) <- c("time", "p", "t", "td", "rh", "u", "v", "spd", "dir", "w", "lon", "lat", "ele", 
                         "azi", "alt", "qp", "qt", "qrh", "qu", "qv", "qdZ", "site", "nominal_launch_time", 
                         "launch_time", "mixr", "ptmp")
    }
    if (site == "Sao Borja, Brazil") {
      out <- out[, ":="(lon = data.table::nafill(lon, "locf"),
                        lat = data.table::nafill(lat, "locf"))]
    }
    
    soundings[[i]] <- out
  }
  soundings <- rbindlist(soundings, fill=TRUE)
}

DewPoint2 <- function (p, ws, td, epsilon = 0.622) 
{
  if (hasArg(p) & hasArg(ws) & !hasArg(td)) {
    if (is.na(ws)) {
      return(ws)
    }
    .dew <- function(td) {
      es <- ClausiusClapeyron(td)
      ws - epsilon * es/(p - es)
    }
    t <- seq(10, 273 + 100, length.out = 100)
    samples <- .dew(t)
    i <- which(samples < 0)[1]
    tm <- t[i]
    
    td <- try(uniroot(.dew, c(10, tm))$root, silent = TRUE)
    if (inherits(td, "try-error"))  {
      browser()    
      
      return(NA_real_)
    }
    return(td)
  }
  else if (hasArg(p) & !hasArg(ws) & hasArg(td)) {
    es <- ClausiusClapeyron(td)
    return(epsilon * es/(p - es))
  }
  else if (!hasArg(p) & hasArg(ws) & hasArg(td)) {
    es <- ClausiusClapeyron(td)
    return(es * (1 + epsilon/ws))
  }
  else if (hasArg(p) & hasArg(ws) & hasArg(td)) {
    stop("Too many state variables.")
  }
  else {
    stop("Too few stat variables.")
  }
}


td <- function(lev, q) {
  # browser()
  lev <- lev*100
  q <- q/1000
  
  td <- if_else(is.na(q) | q < 1e-10, NA_real_, map2_dbl(lev, q, ~ DewPoint2(.x, .y)))
}
```


```{r eval=FALSE}
files <- list.files(path = "/home/paola.corrales/datosmunin3/DATA/RELAMPAGO/sondeos_raw",
                    pattern = "cls", full.names = TRUE)

sondeos <- purrr::map(files, ~ read_radiosonde_relampago(.x)) %>%
  rbindlist() %>% 
  .[site == "M1: Cordoba, Argentina"]

path_npp <- "/datosalertar1/paula.maldonado/RRA_VERIF/data/raw/gfs_raw"
path_out <- "/home/paola.corrales/datosmunin3/RRA_Validacion/interp_sondeos_fcst/"

first_date <- ymd_hms("20181109000000")

dates <- seq(first_date, by = "6 hour",
             length.out = 2) #163


for (d in seq_along(dates)) {
  
  ini_date <- dates[d]
  
  print(ini_date)
  
  lead_time <- c(0:36)
  
  dir <- paste0(path_npp, "/", format(ini_date, "%Y%m%d_%H"), "F")
  
  if (!dir.exists(dir)) {
    next
  }
  
  file_wrf <- paste0(path_npp, "/", 
                     format(ini_date, "%Y%m%d_%H"), "F/NPP_",
                     format(ini_date, "%Y"), "-",
                     format(ini_date, "%m"), "-",
                     format(ini_date, "%d"), "_",
                     format(ini_date, "%H"), "_FC",
                     formatC(lead_time, width = 2, flag = "0"),
                     ".nc")
  
  out <- purrr::map_df(file_wrf, function(f) {  
    
    if (!file.exists(f)) {
      return(NULL)
    }
    # print(basename(f))
    meta <- unglue::unglue(f, "/datosalertar1/paula.maldonado/RRA_VERIF/data/raw/gfs_raw/{fecha_ini}F/NPP_{fecha_ini2}_FC{fcst_hour}.nc")
    
    fcst <- ReadNetCDF(f,
                       vars = c(gp = "yacanto/Z", t = "yacanto/T", u = "yacanto/U", v = "yacanto/V", q = "yacanto/Q")) %>%
      # na.omit() %>%
      .[, ":="(td = td(`yacanto/lev`, q) - 273.15,
               t = t - 273.15,
               fecha_ini = ymd_h(meta[[1]][["fecha_ini"]]),
               fecha = ymd_h(meta[[1]][["fecha_ini"]]) + hours(meta[[1]][["fcst_hour"]]))] %>%
      setnames(c("yacanto/ens", "yacanto/lev"), c("ens", "lev"))
    
    levs <- fcst[ens == 1, lev]
    
    fcst_time <- ymd_h(meta[[1]][["fecha_ini"]]) + hours(meta[[1]][["fcst_hour"]])
    intervalo <- interval(fcst_time - minutes(30), fcst_time + minutes(30))
    
    subset <- sondeos[launch_time %within% intervalo] 
    
    # message(paste0(nrow(subset), " observaciones de sondeos en este tiempo"))
    
    if (nrow(subset) > 1) {
      subset <- subset %>% 
        melt(measure.vars = c("t", "td", "u", "v"), value.name = "obs_value") %>% 
        .[, c("p", "site", "launch_time", "variable", "obs_value")] %>% 
        .[, .(obs_value = mean(obs_value, na.rm = TRUE)), by = .(site, launch_time, variable, p)] %>% 
        
        .[, .(obs_value = approx(p, obs_value, xout = levs)$y,
              lev = levs), 
          by = .(variable)] 
      
      fcst <- fcst %>% 
        melt(measure.vars = c("t", "td", "u", "v"), value.name = "fcst_value") %>% 
        .[, c("ens", "lev", "fecha_ini", "fecha", "variable", "fcst_value")] %>% 
        subset[., on = c("variable", "lev")]
      
    } 
    
  })
  write_csv(out, paste0(path_out, "sondeo_gfs_", format(ini_date, "%Y%m%d_%H"), "F.csv"))
  print("Done!")
}



```

```{r}
interp_files <- Sys.glob(paste0(path_out, "*sondeo_2*"))

sondeos_interp <- map_df(interp_files,  ~ fread(.x)) %>% 
  setDT() %>% 
  .[, fcst_hour := as.numeric((fecha - fecha_ini)/3600)] %>% 
  .[, run := "RRR"] %>% 
  .[, variable := fct_relevel(variable, "u", "v", "t", "td")] %>% 
  .[]

interp_files <- Sys.glob(paste0(path_out, "*gfs*"))

sondeos_interp_gfs <- map_df(interp_files,  ~ fread(.x)) %>% 
  setDT() %>% 
  .[, fcst_hour := as.numeric((fecha - fecha_ini))] %>% 
  .[, run := "NoRegDA"] %>% 
  .[, variable := fct_relevel(variable, "u", "v", "t", "td")] %>% 
  .[]

fisica <- data.table(ens = 1:60,
                     fisica = rep(c("KF-YSU", 
                                    "BMJ-YSU",
                                    "GF-YSU",
                                    "KF-MYJ",
                                    "BMJ-MYJ",
                                    "GF-MYJ",
                                    "KF-MYNN2",
                                    "BMJ-MYNN2",
                                    "GF-MYNN2"), length.out = 60)) %>% 
  separate(fisica, into = c("cumulus", "pbl"), remove = FALSE) %>% 
  setDT()
init <- c()


max_min <- rbind(sondeos_interp[(hour(fecha) == 12 & fcst_hour == 0) | (hour(fecha) == 18 & fcst_hour == 6)],
                 sondeos_interp_gfs[(hour(fecha) == 12 & fcst_hour == 6) | (hour(fecha) == 18 & fcst_hour == 12)]) %>% 
  .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
        bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(ens, variable, lev, sondeo = hour(fecha), fcst_hour, run)] %>% 
  .[sondeo == 12] %>% 
  melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico") %>% 
  .[, ":="(max_v = max(value, na.rm = TRUE),
           min_v = min(value, na.rm =TRUE)), by = .(variable, lev, sondeo, fcst_hour, run, estadistico)] %>% 
  .[is.finite(max_v)]

rbind(sondeos_interp[(hour(fecha) == 12 & fcst_hour == 0) | (hour(fecha) == 18 & fcst_hour == 6)],
      sondeos_interp_gfs[(hour(fecha) == 12 & fcst_hour == 6) | (hour(fecha) == 18 & fcst_hour == 12)]) %>% 
  .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
        bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, sondeo = hour(fecha), fcst_hour, run)] %>% 
  .[sondeo == 12] %>% 
  melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico") %>% 
  # .[, variable := fct_relevel(variable, "u", "v", "t", "td")] %>% 
  ggplot(aes(lev, value)) +
  geom_hline(yintercept = 0, color = "grey90") +
  geom_ribbon(data = max_min, aes(ymin = min_v, ymax = max_v, fill = run, 
                                  group = interaction(run, estadistico, sondeo, fcst_hour)),
              alpha = 0.15) +
  geom_line(aes(color = estadistico, 
                linetype = run, 
                group = interaction(run, estadistico, sondeo, fcst_hour)), size = 0.5) +
  scale_linetype_manual(values = c(2, 1)) +
  scale_color_manual(values = c("black", "grey40")) +
  scale_fill_brewer(guide = NULL, palette = "Set1") +
  coord_flip() +
  scale_x_level(breaks = seq(100, 1000, 100)) +
  facet_wrap(~variable, scales = "free_x",
             labeller = labeller(variable = c("t" = "(c) BIAS & RMSE T [K]",
                                              "td" = "(d) BIAS & RMSE Td [K]",
                                              "u" = "(a) BIAS & RMSE U [ms-1]",
                                              "v" = "(b) BIAS & RMSE V [ms-1]"))) +
  labs(color = NULL, linetype = NULL, x = NULL, y = NULL) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.text = element_text(color = "black"),
        panel.grid = element_line(color = "grey80"),
        panel.grid.major = element_line(color = "grey97"),
        panel.grid.minor = element_line(color = "grey97"),
        legend.position = c(0.90, 0.34),
        legend.box.background = element_rect(fill = NULL,
                                         size = 0.5, linetype = "solid", 
                                         colour = "grey90"),
        # legend.margin = margin(0, 8, 7, 8),
        legend.spacing.y = unit(-0.1, "cm"))

ggsave("opcion1.png", height = 7, width = 7)

init <- c(0, 12, 18)

for (i in init) { 
  
  sondeos_interp[hour(fecha) == i & fcst_hour %in% seq(0, 24, 6)] %>% 
    .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
          bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour)] %>% 
    melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico") %>% 
    ggplot(aes(lev, value)) +
    geom_point(aes(color = factor(fcst_hour)), size = 0.3) +
    geom_line(aes(color = factor(fcst_hour), linetype = estadistico), size = 0.3) +
    coord_flip() +
    scale_x_level() +
    facet_wrap(~variable, scales = "free_x") +
    labs(color = "Forecast\nlead time", linetype = NULL, x = NULL,
         subtitle = paste0("M1: Cordoba - ", i, " UTC")) +
    theme_minimal()
  
  ggsave(paste0("sondeo_gfs_", i, "UTC.png"), height = 7, width = 7)
  
  
  sondeos_interp[hour(fecha) == i & fcst_hour %in% seq(0, 24, 6)] %>% 
    fisica[., on = .NATURAL] %>% 
    .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
          bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour, cumulus)] %>% 
    melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico") %>% 
    ggplot(aes(lev, value)) +
    geom_point(aes(color = factor(fcst_hour)), size = 0.1) +
    geom_line(aes(color = factor(fcst_hour), linetype = estadistico), size = 0.3) +
    coord_flip() +
    scale_x_level() +
    facet_grid(cumulus~variable, scales = "free_x") +
    labs(color = "Forecast\nlead time", linetype = NULL, x = NULL,
         subtitle = paste0("M1: Cordoba - ", i, " UTC")) +
    theme_minimal()
  
  ggsave(paste0("sondeo_cumulus_", i, "UTC.png"), height = 7, width = 8)
  
  sondeos_interp[hour(fecha) == i & fcst_hour %in% seq(0, 24, 6)] %>% 
    fisica[., on = .NATURAL] %>% 
    .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
          bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour, pbl)] %>% 
    melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico") %>% 
    ggplot(aes(lev, value)) +
    geom_point(aes(color = factor(fcst_hour)), size = 0.1) +
    geom_line(aes(color = factor(fcst_hour), linetype = estadistico), size = 0.3) +
    coord_flip() +
    scale_x_level() +
    facet_grid(pbl~variable, scales = "free_x") +
    labs(color = "Forecast\nlead time", linetype = NULL, x = NULL,
         subtitle = paste0("M1: Cordoba - ", i, " UTC")) +
    theme_minimal()
  
  ggsave(paste0("sondeo_pbl__gfs", i, "UTC.png"), height = 7, width = 8)
  
}

```

```{r}
rmse_12 <- sondeos_interp[hour(fecha_ini) == 12 & fcst_hour %in% c(0, 6, 9, 3, 12)] %>% 
  .[, .(rmse_12 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_9 <- sondeos_interp[hour(fecha_ini) == 9 & fcst_hour %in% c(3, 9, 12, 6, 15)] %>% 
  .[, .(rmse_9 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_18 <- sondeos_interp[hour(fecha_ini) == 18 & fcst_hour %in% c(0, 3, 6, 18, 21)] %>% 
  .[, .(rmse_18 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_15 <- sondeos_interp[hour(fecha_ini) == 15 & fcst_hour %in% c(3, 6, 9, 21, 24)] %>% 
  .[, .(rmse_15 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_0 <- sondeos_interp[hour(fecha_ini) == 0 & fcst_hour %in% c(0, 12, 15, 18, 21)] %>% 
  .[, .(rmse_0 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_21 <- sondeos_interp[hour(fecha_ini) == 21 & fcst_hour %in% c(3, 15, 18, 21, 24)] %>% 
  .[, .(rmse_21 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_6 <- sondeos_interp[hour(fecha_ini) == 6 & fcst_hour %in% c(6, 9, 12, 15, 18)] %>% 
  .[, .(rmse_6 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 

rmse_3 <- sondeos_interp[hour(fecha_ini) == 3 & fcst_hour %in% c(9, 12, 15, 18, 21)] %>% 
  .[, .(rmse_3 = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE))), by = .(variable, lev)] 




rbind(rmse_12[rmse_9, on = .NATURAL] %>% 
        .[, ":="(diff = rmse_12 - rmse_9,
                 time = "12-09 UTC")] %>% 
        .[, ":="(rmse_12 = NULL,
                 rmse_9 = NULL)],
      
      rmse_18[rmse_15, on = .NATURAL] %>% 
        .[, ":="(diff = rmse_18 - rmse_15,
                 time = "18-15 UTC")] %>% 
        .[, ":="(rmse_18 = NULL,
                 rmse_15 = NULL)],
      
      rmse_0[rmse_21, on = .NATURAL] %>% 
        .[, ":="(diff = rmse_0 - rmse_21,
                 time = "00-21 UTC")] %>% 
        .[, ":="(rmse_0 = NULL,
                 rmse_21 = NULL)],
      
      rmse_6[rmse_3, on = .NATURAL] %>% 
        .[, ":="(diff = rmse_6 - rmse_3,
                 time = "06-03 UTC")] %>% 
        .[, ":="(rmse_6 = NULL,
                 rmse_3 = NULL)]) %>% 
  .[, variable := fct_relevel(variable, "u", "v", "t", "td")] %>% 
  ggplot(aes(lev, diff)) +
  geom_hline(yintercept = 0, color = "grey90") +
  geom_line(aes(color = time)) +
  geom_point(aes(shape = time, color = time), size = 1) +
  coord_flip() +
  scale_color_manual(values = c("#000000", "#A9A9A9", "#C0C0C0", "#696969")) +
  scale_shape_manual(values = c(16, 15, 17, 18)) +
  scale_x_level(breaks = seq(100, 1000, 100)) +
  facet_wrap(~variable, scales = "free_x", labeller = labeller(variable = c("t" = "(c) RMSE diff T [K]",
                                                                            "td" = "(d) RMSE diff Td [K]",
                                                                            "u" = "(a) RMSE diff U [ms-1]",
                                                                            "v" = "(b) RMSE diff V [ms-1]"))) +
  labs(color = NULL, shape = NULL, y = NULL) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.text = element_text(color = "black"),
        panel.grid = element_line(color = "grey80"),
        panel.grid.major = element_line(color = "grey97"),
        panel.grid.minor = element_line(color = "grey97"),
        legend.position = c(0.9, 0.35),
        legend.background = element_rect(fill = NULL,
                                         size = 0.5, linetype = "solid", 
                                         colour = "grey90"),
        legend.margin = margin(0, 8, 7, 8))

ggsave("diff_rmse_variables.png", height = 7, width = 7)


```


```{r}
fecha_ini_fcst <- 12

ini_12 <- sondeos_interp[hour(fecha_ini) == 12 & fcst_hour %in% c(0, 6, 12, 24)] %>% 
  .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
        bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour)] %>% 
  .[, radiosonde := fcase(fcst_hour == 0, "12 UTC",
                          fcst_hour == 6, "18 UTC",
                          fcst_hour == 12, "00 UTC",
                          fcst_hour == 24, "12 UTC next day")] %>% 
  .[, hora_ini := 12] %>% 
  melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico")


ini_9 <- sondeos_interp[hour(fecha_ini) == 9 & fcst_hour %in% c(3, 9, 15, 27)] %>% 
  .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
        bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour)] %>% 
  .[, radiosonde := fcase(fcst_hour == 3, "12 UTC",
                          fcst_hour == 9, "18 UTC",
                          fcst_hour == 15, "00 UTC",
                          fcst_hour == 27, "12 UTC next day")] %>% 
  .[, hora_ini := 9] %>% 
  melt(measure.vars = c("rmse", "bias"), variable.name = "estadistico")

rbind(ini_9, ini_12) %>%  
  ggplot(aes(lev, value)) +
  geom_hline(aes(yintercept = 0), color = "grey 40") +
  # geom_point(aes(color = factor(hora_ini)), size = 0.3) +
  geom_line(aes(color = factor(hora_ini), linetype = estadistico), size = 0.3) +
  # scale_color_discrete(labels = c("0" = "12 UTC", "6" = "18 UTC", "12" = "00 UTC", "24" = "12 UTC next day")) +
  coord_flip() +
  scale_x_level() +
  facet_grid(radiosonde~variable, scales = "free_x") +
  labs(color = "Forecast initialization", linetype = NULL, x = NULL, y = NULL) +
  theme_minimal()

ggsave(paste0("sondeos_gfs_init_9_12_UTC.png"), height = 7, width = 9)
```


```{r}
rbind(ini_9, ini_12) %>%  
  .[, estadistico := paste0(toupper(estadistico), hora_ini)] %>% 
  dcast(variable + lev + radiosonde ~ estadistico, value.var = "value") %>%
  .[, ":="(RMSE12_RMSE9 = RMSE12 - RMSE9,
           BIAS12_BIAS9 = BIAS12 - BIAS9)] %>%
  .[] %>% 
  ggplot(aes(lev, RMSE12_RMSE9)) +
  geom_hline(aes(yintercept = 0), color = "grey 40") +
  geom_line(aes(color = radiosonde), size = 0.4) +
  coord_flip() +
  scale_x_level() +
  facet_grid(.~variable, scales = "free_x") +
  labs(color = "Radiosonde\nlaunch time", linetype = NULL, x = NULL, y = NULL,
       subtitle = "RMSE12 - RMSE09") +
  theme_minimal()

ggsave("RMSE12_RMSE9_gfs.png", height = 4, width = 7)

rbind(ini_9, ini_12) %>%  
  .[, estadistico := paste0(toupper(estadistico), hora_ini)] %>% 
  dcast(variable + lev + radiosonde ~ estadistico, value.var = "value") %>%
  .[, ":="(RMSE12_RMSE9 = RMSE12 - RMSE9,
           BIAS12_BIAS9 = BIAS12 - BIAS9)] %>%
  .[] %>% 
  ggplot(aes(lev, BIAS12_BIAS9)) +
  geom_hline(aes(yintercept = 0), color = "grey 40") +
  geom_line(aes(color = radiosonde), size = 0.7) +
  coord_flip() +
  scale_x_level() +
  facet_grid(.~variable, scales = "free_x") +
  labs(color = "Radiosonde\nlaunch time", linetype = NULL, x = NULL, y = NULL,
       subtitle = "BIAS12 - BIAS09") +
  theme_minimal()
```


```{r}

# fecha_ini == as_datetime("2018-11-10 00:00:00 UTC") 
sondeos_interp[ens == 1 & hour(fecha) %in% c(0, 12, 18) & fcst_hour %in% c(0, 6, 12) & variable == "t" & lev > 500] %>% 
  # melt(measure.vars = c("obs_value", "fcst_value"), variable.name = "run") %>% 
  .[, fecha_ini := factor(fecha)] %>% 
  # .[, .(rmse = sqrt(mean((fcst_value - obs_value)^2, na.rm = TRUE)),
  #       bias = mean(fcst_value - obs_value, na.rm = TRUE)), by = .(variable, lev, fcst_hour)] %>% 
  #  melt(measure.vars = c("rmse", "bias"), variable.name = "run") %>% 
  ggplot(aes(fcst_value, obs_value)) +
  # geom_line(aes(linetype = run)) +
  
  geom_point(aes(color = factor(lev))) +
  geom_abline(intercept = 0, slope = 1) +
  scale_color_viridis_d() +
  # coord_flip() +
  # scale_x_level() +
  facet_grid(fcst_hour~hour(fecha), scales = "free_x")
```





